# Generated by Django 2.0.7 on 2019-04-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='id',
        ),
        migrations.RemoveField(
            model_name='corretor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='id',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mensagens',
            name='id',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='id',
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='id_aluguel',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='id_boleto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contato',
            name='id_contato',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='id_corretor',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_endereco',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='id_imovel',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mensagens',
            name='id_mensagens',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venda',
            name='id_venda',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
