# Generated by Django 2.0.7 on 2019-04-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='id_corretor',
            field=models.ForeignKey(blank=True, db_column='id_corretor', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Corretor'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='id_proprietario',
            field=models.ForeignKey(blank=True, db_column='id_proprietario', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Proprietario'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_corretor',
            field=models.ForeignKey(blank=True, db_column='id_corretor', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Corretor'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_imovel',
            field=models.ForeignKey(blank=True, db_column='id_imovel', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Imovel'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_proprietario',
            field=models.ForeignKey(blank=True, db_column='id_proprietario', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Proprietario'),
        ),
    ]
