# Generated by Django 2.0.7 on 2019-04-17 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
    ]
