# Generated by Django 2.0.7 on 2019-04-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='contato',
            name='id_proprietario',
            field=models.ForeignKey(blank=True, db_column='id_proprietario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Proprietario'),
        ),
    ]
