# Generated by Django 2.0.7 on 2019-04-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id_aluguel', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_propietario', models.IntegerField(blank=True, null=True)),
                ('id_imovel', models.IntegerField(blank=True, null=True)),
                ('id_corretor', models.IntegerField(blank=True, null=True)),
                ('data_aluguel', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_aluguel', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aluguel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id_boleto', models.AutoField(primary_key=True, serialize=False)),
                ('id_aluguel', models.IntegerField(blank=True, null=True)),
                ('id_venda', models.IntegerField(blank=True, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_propietario', models.IntegerField(blank=True, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_boleto', models.FloatField(blank=True, null=True)),
                ('multa_juros', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'boleto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id_contato', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('propietario', models.IntegerField(blank=True, null=True)),
                ('id_corretor', models.IntegerField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contato',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id_corretor', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=100, null=True)),
                ('registro', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'corretor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_imovel', models.IntegerField(blank=True, null=True)),
                ('id_propietario', models.IntegerField(blank=True, null=True)),
                ('id_corretor', models.IntegerField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'endereco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id_imovel', models.AutoField(db_column='Id_imovel', primary_key=True, serialize=False)),
                ('id_propietario', models.IntegerField(blank=True, db_column='Id_propietario', null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('iptu', models.CharField(blank=True, max_length=100, null=True)),
                ('metro_quadrado', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imovel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('id_mensagens', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_propietario', models.IntegerField(blank=True, null=True)),
                ('id_corretor', models.IntegerField(blank=True, null=True)),
                ('assunto', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_envio', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mensagens',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_propietario', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'propietario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_propietario', models.IntegerField(blank=True, null=True)),
                ('id_imovel', models.IntegerField(blank=True, db_column='Id_imovel', null=True)),
                ('id_corretor', models.IntegerField(blank=True, null=True)),
                ('data_venda', models.DateField(blank=True, null=True)),
                ('valor_imovel', models.FloatField(blank=True, null=True)),
                ('valor_venda', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'venda',
                'managed': True,
            },
        ),
    ]
