# Generated by Django 2.0.7 on 2019-04-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluguel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='boleto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contato',
            options={},
        ),
        migrations.AlterModelOptions(
            name='corretor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mensagens',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={},
        ),
        migrations.AlterModelTable(
            name='aluguel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='boleto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='contato',
            table=None,
        ),
        migrations.AlterModelTable(
            name='corretor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='endereco',
            table=None,
        ),
        migrations.AlterModelTable(
            name='imovel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mensagens',
            table=None,
        ),
        migrations.AlterModelTable(
            name='propietario',
            table=None,
        ),
        migrations.AlterModelTable(
            name='venda',
            table=None,
        ),
    ]
