# Generated by Django 2.0.7 on 2018-11-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(blank=True, max_length=150)),
                ('celular_responsavel', models.IntegerField(null=True)),
                ('endereco', models.CharField(blank=True, max_length=150)),
                ('cep', models.IntegerField(blank=True)),
                ('valor_compra', models.CharField(blank=True, max_length=150)),
                ('valor_aluguel', models.CharField(blank=True, max_length=150)),
                ('descricao_imovel', models.TextField(blank=True)),
            ],
        ),
    ]
