# Generated by Django 2.0.7 on 2019-04-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190407_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluguel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='boleto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contato',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='corretor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mensagens',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='aluguel',
            table='aluguel',
        ),
        migrations.AlterModelTable(
            name='boleto',
            table='boleto',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='contato',
            table='contato',
        ),
        migrations.AlterModelTable(
            name='corretor',
            table='corretor',
        ),
        migrations.AlterModelTable(
            name='endereco',
            table='endereco',
        ),
        migrations.AlterModelTable(
            name='imovel',
            table='imovel',
        ),
        migrations.AlterModelTable(
            name='mensagens',
            table='mensagens',
        ),
        migrations.AlterModelTable(
            name='propietario',
            table='propietario',
        ),
        migrations.AlterModelTable(
            name='venda',
            table='venda',
        ),
    ]
