# Generated by Django 2.0.7 on 2018-11-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_imoveis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='foto',
        ),
    ]
